### ISSUE TITLE
Livekit importing err when working with nestjs.

### ISSUE THREAD

**Issue by jossephus** [livekit/server-sdk-js#178] opened 2024-05-06 11:35 UTC
I am getting error

```
const livekit_server_sdk_1 = require("livekit-server-sdk");
                             ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/aldrich/temp/nest/livekit-server/node_modules/.pnpm/livekit-server-sdk@2.3.0/node_modules/livekit-server-sdk/dist/index.js from /home/
aldrich/temp/nest/livekit-server/dist/app.service.js not supported.
Instead change the require of index.js in /home/aldrich/temp/nest/livekit-server/dist/app.service.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/aldrich/temp/nest/livekit-server/dist/app.service.js:11:30)
    at Object.<anonymous> (/home/aldrich/temp/nest/livekit-server/dist/app.controller.js:14:23)
    at Object.<anonymous> (/home/aldrich/temp/nest/livekit-server/dist/app.module.js:11:26)
    at Object.<anonymous> (/home/aldrich/temp/nest/livekit-server/dist/main.js:4:22)
```

when I try to import livekit from a nestjs backend.

Steps for Reproduction:

1. git clone [https://github.com/jossephus/livekit-with-nestjs](https://github.com/jossephus/livekit-with-nestjs)
2. cd livekit-with-nestjs && pnpm install
3. pnpm start:dev

further info: this is the only place I am using Livekit sdk

![image](https://uploads.linear.app/65f9603c-a265-4a1f-8af0-4c2243b87ade/ab3121c1-aabd-44d4-bac2-40e1f0bd6336/15ff0142-71d6-4a21-a781-bb041f7fd8a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY1Zjk2MDNjLWEyNjUtNGExZi04YWYwLTRjMjI0M2I4N2FkZS9hYjMxMjFjMS1hYWJkLTQ0ZDQtYmFjMi00MGUxZjBiZDYzMzYvMTVmZjAxNDItNzFkNi00YTIxLWE3ODEtYmIwNDFmN2ZkOGE5IiwiaWF0IjoxNzE0OTk2MjMyLCJleHAiOjMzMjg1NTU2MjMyfQ.QKb0XDvK7g7UU2E7UX\_-wn9XNpoGPDPi8slmypQzejg)

**Comment by lukasIO** [comment] 2024-05-06 11:51
duplicate of https://github.com/livekit/server-sdk-js/issues/139

**Closed by lukasIO** 2024-05-06 11:51 UTC
